### ISSUE TITLE
using the element as JS module

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/ikonograph#52]
hi, just using Ikonograph 😄 on a JS module environment with Webpack, I had to figure it out that the right way to import the custom element as a JS module is:

```javascript
import 'ikonograph/dist/ikonograph';
```

which is a undocumented so maybe you can add it as information in the readme, to make it quicker for newcomers.

**Bonus point** could be renaming the file to something a bit less redundant and more meaningful like:

```javascript
import 'ikonograph/dist/element';
```

yo! 😎

**Comment by equinusocio** [comment]
Hi @moebiusmania, are you using ikonograph as module without any other issues?

**Comment by moebiusmania** [comment]
@equinusocio yep, its fine!
